/*
  BASE DE LANÇAMENTOS — fonte: "LANÇAMENTOS CAMPINAS 2026 ATUALIZADO" (PDF ZFF)
  Para atualizar: edite/adicione objetos abaixo. Campos:
    n  = nome do empreendimento        c  = construtora
    b  = bairro                         t  = "apto" | "casa"
    m  = metragens em m² (lista)        d  = [dorms mín, dorms máx] (null = não informado)
    su = true se as unidades são suítes v  = vagas (texto)
    e  = entrega "AAAA-MM" | "pronto"   el = rótulo opcional da entrega
    p  = preços médios: [[m², valor em R$ mil | null = esgotado], ...]  (m² null = valor geral)
    vis = "stand_dec" | "stand" | "torre" | "imovel" | "dec" | "virtual" | "nenhum"
    vo = observação da visita            tip = tipologia extra   obs = observações
    end = endereço   ficha = [["rótulo","valor"], ...]   lazer = ["item", ...]   (seção "Sobre o empreendimento")

  CAMPOS QUE O PDF NÃO TRAZ (preencha quando souber; sem o campo = "não informado"):
    vc    = tipo de vaga: "coberta" | "descoberta" | "ambas"
    fgts  = aceita FGTS na entrada: true | false
    inv   = ótimo para investimento: true | false
    suite = tem suíte: true | false   (projetos com su:true já contam como "tem suíte")

  COMPARADOR (#/comparar) — dados tirados do book, usados para preencher o comparativo:
    cmp = { ter: terreno, tor: torres, un: total de unidades, el: elevadores, var: varanda, dif: diferenciais da unidade,
            st: status, end/m2: substituem endereço/metragem no comparativo }
  Ex.: { n:"Lazur", ..., vc:"coberta", fgts:true, inv:true, suite:true },
*/
window.ATUALIZADO_EM = "Out/2026";

window.LANCAMENTOS = [
  // ── MANSÕES SANTO ANTÔNIO ─────────────────────────────
  { n:"Alentejo", c:"Riva", b:"Mansões Santo Antônio", t:"apto", m:[58,74], d:[2,3], v:"1 e 2", e:"2027-06", p:[[null,800]], vis:"stand" },
  { n:"San Pietro", c:"Caprem", b:"Mansões Santo Antônio", t:"apto", m:[51,60], d:[2,3], v:"1 (vinculada)", vc:"ambas", e:"2027-12", p:[[null,620]], vis:"stand_dec",
    cmp:{ter:"10.756,27 m²", tor:"4 (A, B, C e D)", var:"Sim — ponto de gás para grill ou cooktop (suporta fechamento)", dif:"Previsão de ar-condicionado na sala e dormitórios · água quente a gás nos chuveiros e na pia da cozinha · persiana integrada nos dormitórios · laje técnica · pé-direito de 2,70 m"},
    tip:"Plantas de 51 m² e 60 m² (2 e 3 dormitórios) · previsão de ar-condicionado na sala e dormitórios · ponto de água quente nos chuveiros e na pia da cozinha",
    end:"Rua Lauro Vannucci, 381 — Parque Rural Fazenda Santa Cândida",
    ficha:[["Torres","4 (A, B, C e D)"],["Garagem","Edifício-garagem: subsolo (cobertas e algumas descobertas), térreo (cobertas) e 1º andar (descobertas) · vagas vinculadas"],["Terreno","10.756,27 m²"],["Área construída","20.343,57 m²"],["Estrutura","Concreto armado e alvenaria estrutural"]],
    lazer:["Piscina","Churrasqueiras 1 e 2","Salão de festas","Sala de jogos","Espaço fitness","Brinquedoteca","Playground","Campo gramado","Pet place","Praça e espaço leitura","Office lounge","Espaço bem-estar"] },
  { n:"Lazur", c:"Tegra", b:"Mansões Santo Antônio", t:"apto", m:[57,70,78,85,97,115,116], d:[2,3], suite:true, v:"1 ou 2", vc:"coberta", e:"2027-08", p:[[57,590],[70,710]], vis:"stand_dec",
    tip:"57 m² (2 dorms, 1 suíte) e 70 m² (3 dorms, 1 suíte, ou sala ampliada) · penthouses de 78 a 116 m² · ponto grill · sala e dormitórios com piso laminado · persianas de enrolar",
    end:"Rua Prof. Nogueira Braga, 51 — Mansões Santo Antônio",
    ficha:[["Unidades","156 em 1 torre (11 pavimentos tipo + penthouse, 12 por andar): 95 de 57 m², 48 de 70 m² e 13 penthouses"],["Garagem","Edifício-garagem (4 sub/sobressolos) · 1 vaga (57 e 70 m²) ou 2 vagas (penthouses)"],["Elevadores","5 (4 na torre e 1 no edifício-garagem)"],["Terreno","4.701,16 m²"],["Arquitetura","LE Arquitetos"],["Paisagismo","Neusa Nakata"],["Interiores","Bohrer Arquitetos + Claudia Albertini"],["Certificação","AQUA-HQE"]],
    lazer:["Piscina com raia de 20 m e piscina infantil","Quadra poliesportiva","Espaço gourmet e churrasqueira","Salão de festas","Salão de jogos","Brinquedoteca e playground","Pet place","Praças","Bicicletário decorado","Delivery space","Mini market"],
    cmp:{ter:"4.701,16 m²", tor:"1 + edifício-garagem", un:"156", el:"5 (4 na torre e 1 no ed. garagem)", var:"Sim — com ponto grill", dif:"Previsão para ar-condicionado na sala e dormitórios · persianas de enrolar · piso laminado · previsão para lava-louças · medição de água individualizada · carregador de carro elétrico"} },
  { n:"Liv Mansões", c:"ADN", b:"Mansões Santo Antônio", t:"apto", m:[47], d:[2,2], v:"1 e 2", e:"2028-04", p:[[null,520]], vis:"stand_dec" },
  { n:"High Life", c:"Aliança (Valadares Gontijo)", b:"Mansões Santo Antônio", t:"apto", m:[67.7,134.9], d:[2,3], suite:true, v:"2 + box (duplex: 3)", vc:"coberta", e:"2028-03", p:[[null,760]], vis:"stand_dec",
    tip:"67,70 m² com 2 dorms (1 suíte), varanda gourmet, 2 vagas e box privativo · 4 coberturas duplex de 134,90 m² com 3 dorms (2 suítes), espaço gourmet e terraço descoberto, 3 vagas",
    end:"Rua José Luiz Camargo Moreira, 123 — Mansões Santo Antônio",
    ficha:[["Unidades","62: 58 de 67,70 m² e 4 duplex de 134,90 m²"],["Torre","20 pavimentos com 2 subsolos, 2 elevadores"],["Garagem","131 vagas cobertas em 2 subsolos + 62 boxes privativos, car wash"],["Terreno","2.500 m²"],["Acabamento","Porcelanato na área social e privativa, bancadas em granito"]],
    lazer:["Piscina de raia com deck molhado","Piscina infantil","Espaço gourmet e parrilla","Salão de festas","Wine bar","Espaço fitness","Espaço wellness","Espaço kids e playground","Office","Quadra de beach tennis","Praça de boas-vindas","Pet place"],
    cmp:{ter:"2.500 m²", tor:"1 (20 pavimentos)", un:"62", el:"2", var:"Sim — varanda gourmet", dif:"Box privativo na garagem · 2 vagas cobertas · coberturas duplex com terraço · porcelanato"} },
  { n:"Yees Mansões", c:"Yees (JJR Empreendimentos)", b:"Mansões Santo Antônio", t:"apto", m:[34,53,55], d:[1,2], v:"1 + depósito", e:"2027-07", p:[[null,570]], vis:"stand",
    tip:"Mansões Residencial · 34 m² com 1 dormitório · 53 e 55 m² com 2 dorms (1 suíte) · varanda gourmet com ponto para grill elétrico, piso nivelado com a sala · aquecedor a gás e ponto para ar-condicionado",
    end:"Rua João Preda, 239 — Parque Rural Fazenda Santa Cândida",
    ficha:[["Unidades","113 em torre única (10 por andar)"],["Vagas","113 + 4 PCD + 2 rotativas + 6 de moto · 113 depósitos · ponto para carro elétrico"],["Terreno","3.000 m²"],["Área construída","8.537,69 m²"],["Elevadores","2"],["Sustentabilidade","Medições individuais de gás, água e energia · infra para aquecimento solar/fotovoltaica"]],
    lazer:["Rooftop no 11º pavimento","Piscina com prainha e piscina infantil","Sauna","Academia","Salão de festas e coworking","Churrasqueira integrada ao salão","Lareira","Brinquedoteca e jogos","Playground","Lockers e espaço Uber"],
    cmp:{ter:"3.000 m²", tor:"1", un:"113", el:"2", var:"Sim — varanda gourmet com ponto para grill elétrico", dif:"Depósito por unidade · tomadas USB · aquecedor a gás · ponto para ar-condicionado · lazer no rooftop"} },
  { n:"Be Mansões", c:"Vertaz", b:"Mansões Santo Antônio", t:"apto", m:[42], d:[1,2], v:"1", e:"2027-12", p:[[null,480]], vis:"nenhum" },
  { n:"Cores da Mata", c:"Direcional e Acro", b:"Mansões Santo Antônio", t:"apto", m:[45.28,46.69], d:[2,2], suite:true, v:"1", vc:"coberta", e:"2028-06", p:[[null,450]], vis:"stand_dec",
    cmp:{ter:"8.564,58 m²", tor:"2 (térreo + 18 pavimentos)", un:"300", var:"Sim — varanda grill (ponto elétrico para grill)", dif:"Previsão de ar-condicionado · infra para aquecedor de passagem e chuveiro a gás · bancadas de granito · piso cerâmico · laje técnica · opção de garden no térreo"},
    tip:"2 dormitórios com suíte (exceto PCD) e varanda grill · plantas de 45,28 m² (ponta) e 46,69 m² (meio) · gardens no térreo com 5,96 m² ou 17,47 m² de área descoberta",
    end:"Rua Dois, 115 — Residencial Reserva Villa Bella",
    ficha:[["Unidades","300 em 2 torres (térreo + 18 pavimentos)"],["Por andar","8 apartamentos (6 gardens no térreo)"],["Vagas","Cobertas, não vinculadas às unidades"],["Complexo","Mangará Campinas: mais de 68 mil m², com ~29 mil m² de mata preservada e parque linear"],["Terreno","8.564,58 m²"],["Sistema","Paredes de concreto · pé-direito 2,52 m"],["Localização","250 m do Parque Dom Pedro Shopping"]],
    lazer:["Piscina adulto com deck molhado","Piscina infantil e solário","Academia e fitness externo","Salão de festas","Espaço gourmet e lounge gourmet","Churrasqueira com lounge","Pub e lounge wine","Coworking","Mini quadra","Playground e jogos","Pet place","Bike sharing","Lavanderia","Mini market","Vaga para carro elétrico","Parque linear com pomar e caminho aromático"] },
  { n:"Alta Vista", c:"Direcional e Acro", b:"Mansões Santo Antônio", t:"apto", m:[46,48], d:[2,2], suite:true, v:"1 (vinculada)", vc:"ambas", e:"2029-06", p:[[null,490]], vis:"stand_dec",
    cmp:{tor:"2", var:"Sim — varanda grill em todas as unidades", dif:"Previsão de ar-condicionado · infra para aquecedor de passagem e chuveiro a gás · bancadas de granito · piso cerâmico · opção de garden no térreo (55 e 66 m²)"},
    tip:"Alta Vista Mangará · 2 dormitórios com suíte e varanda grill · plantas de 46 m² (ponta) e 48 m² (meio) · gardens no térreo com 55 m² e 66 m² · opção de vaga coberta",
    ficha:[["Complexo","Mangará Campinas (3º residencial): mais de 68 mil m², ~29 mil m² de mata preservada e parque linear de 4.400 m²"],["Vagas","Vinculadas às unidades, com opção de vaga coberta"],["Localização","2 min do Shopping Dom Pedro · 3 min do The Mall Villa Bella · 6 min da Unicamp"]],
    lazer:["Piscina adulto e infantil com deck","Academia com lounge","Espaço pilates","Quadra de areia recreativa","Salão de festas","Lounge gourmet","Churrasqueira com lounge","Wine lounge","Coworking / espaço influencer","Brinquedoteca","Playground","Praça de convívio e piquenique","Pet place","Bike sharing","Mini market","Vaga para carro elétrico","Parque linear com pomar e caminho aromático"] },
  { n:"Alto das Mansões", c:"PAGV", b:"Mansões Santo Antônio", t:"apto", m:[30.58,31.02,62.04], d:[1,2], v:"1 (direito de uso, com manobrista)", e:"2029-10", p:[[null,350]], vis:"stand_dec",
    cmp:{ter:"2.000 m²", tor:"1 (térreo + 24 pavimentos)", un:"188", var:"Sim — com ponto de grill elétrico", dif:"Infra de ar-condicionado com rede frigorígena na sala e quarto · infra de água quente na cozinha e banheiro · tomadas USB · piso cerâmico/porcelanato · bancadas em granito ou mármore · persiana blackout no quarto · gestão de locação Housi"},
    tip:"Studios de 30,58 a 31,02 m² · 4 studios com Sky Garden (31,02 m² + 30,71 m² de jardim) · 7 coberturas duplex de 2 quartos (62,04 m²) · Powered by Housi (gestão de locação)",
    end:"Rua Prof. Luiz de Pádua, 185 — Santa Cândida",
    ficha:[["Unidades","188 residenciais em torre única (térreo + 24 pavimentos)"],["Studios","177 unidades de 30,58 a 31,02 m²"],["Studios Sky Garden","4 unidades de 31,02 m² + jardim de 30,71 m²"],["Duplex","7 coberturas de 2 quartos com 62,04 m²"],["Garagem","Com manobrista: 138 vagas de carro (2 descobertas), 4 PCD e 33 de moto"],["Lojas","5 lojas no térreo com pé-direito duplo"],["Terreno","2.000 m²"],["Locação","Parceria Housi (Vitacon) para gestão de aluguel"]],
    lazer:["Casa de Campo com churrasqueira, WC e piscina privativa","Piscina com deck molhado","Quadra de beach tennis e lounge","Gourmet com Steak House","Lounge gourmet","Academia","Sauna","Coworking / meeting room","Mini mercado","Laundry","Praça pet","Wine lounge","Hall instagramável","Bicicletário"] },
  { n:"WYN Residence", c:"Acro (Grupo Sartori)", b:"Mansões Santo Antônio", t:"apto", m:[77.5,94.7], d:[2,3], suite:true, v:"2", vc:"coberta", e:"2029-01", p:[[77.5,865],[94.7,1200]], vis:"stand_dec",
    tip:"77,50 m²: 2 suítes, lavabo e varanda gourmet · 94,70 m²: 3 dorms (1 suíte), lavabo, varanda gourmet e cozinha aberta com ilha · 2 vagas cobertas · churrasqueira a gás na varanda (infra) · fechadura digital",
    end:"Av. Ricardo Rocha Bonfim, 294 — Residencial Vila Bella D. Pedro",
    ficha:[["Unidades","164 em 3 torres: 112 de 94,70 m² (torres 1 e 2, 14 pavimentos) e 52 de 77,50 m² (torre 3, 13 pavimentos)"],["Garagem","Edifício-garagem com 2 níveis · 2 vagas cobertas por apartamento"],["Terreno","15.988,34 m² (condomínio clube)"],["Unidades","Infra para ar-condicionado na sala e dormitórios, persianas integradas, infra para recarga de carro elétrico"]],
    lazer:["Piscinas adulto e infantil","Salão de festas","Espaço gourmet","Churrasqueiras","Espaços fitness","Quadras de esportes","Fireplace e praça happy hour","Praça multiuso e praça dos esportes","Áreas kids e pet place","Coworking","Espaço delivery climatizado","Home market","Horta","Bicicletário"],
    cmp:{ter:"15.988,34 m²", tor:"3 (13 e 14 pavimentos)", un:"164", var:"Sim — varanda gourmet com infra para churrasqueira a gás", dif:"Fechadura digital · persianas integradas · infra para ar-condicionado · entradas social e de serviço independentes (94,70 m²) · cozinha aberta com ilha"} },
  { n:"Freedom", c:"Ytcon", b:"Mansões Santo Antônio", t:"apto", m:[66], d:[2,3], v:"1", e:"2028-03", p:[[null,640]], vis:"stand_dec" },

  // ── NOVA CAMPINAS ─────────────────────────────────────
  { n:"Vista Horizonte", c:"Tegra", b:"Nova Campinas", t:"apto", m:[60,76.5], d:[2,3], suite:true, v:"1 ou 2", vc:"coberta", e:"2027-09", p:[[60,630],[76.5,820]], vis:"torre",
    cmp:{ter:"4.669,82 m²", tor:"1 (34 andares)", un:"272", el:"5 (4 sociais e 1 de serviço)", var:"Sim — terraço", dif:"Aquecimento de água nos chuveiros · bacias com duplo acionamento · opcionais Tegra ID (planta, acabamentos, fechadura eletrônica, churrasqueira a carvão, rede frigorígena p/ ar-condicionado)"},
    tip:"60 m²: 2 dorms (1 suíte) ou sala ampliada com 1 suíte · 76,5 m²: 3 dorms (1 suíte) ou sala ampliada com 2 suítes · 12 unidades de 76,5 m² com 2 vagas",
    end:"Rua Maestro Agide Azzoni, 295 — Chácara da Barra (entre o Cambuí e Nova Campinas)",
    ficha:[["Unidades","272 em torre única de 34 andares (8 por andar)"],["60 m²","136 unidades · 1 suíte · 1 vaga"],["76,5 m²","124 unidades com 1 vaga + 12 com 2 vagas · 1 suíte"],["Garagem","Edifício-garagem (2 subsolos ao 1º pavimento), vagas vinculadas"],["Elevadores","5 (4 sociais e 1 de serviço)"],["Terreno","4.669,82 m²"],["Arquitetura","Primi & Appoloni"],["Decoração","Bohrer Arquitetos"],["Paisagismo","Marcelo Novaes"],["Certificação","AQUA-HQE (sustentabilidade)"]],
    lazer:["Family Pool com piscinas adulto e infantil e solário","Play Aventura","Quadra esportiva","Churrasqueira","Salão de festas","Festas gourmet","Lounge Square","Praça Boas-Vindas","Fit Place (academia) e fitness externo","Brinquedoteca","Game Room","Bicicletário decorado","Espaço delivery","Infraestrutura para carro elétrico","Controle de acesso e CFTV"] },
  { n:"Frame", c:"Vanguard (Grupo Plaenge)", b:"Nova Campinas", t:"apto", m:[50,84,118], d:[1,3], v:"1 ou 2", vc:"coberta", e:"2028-06", p:[[50,630],[84,950],[118,1500]], vis:"stand_dec",
    tip:"50 m²: 1 dormitório, lavabo e varanda · 84 m²: 2 dorms (1 suíte) com varanda com churrasqueira · 118 m²: 3 dorms (1 suíte), lavabo e varanda com churrasqueira · vaga extra sob consulta",
    end:"Rua Rafael Andrade Duarte, 208 — Nova Campinas (2º acesso: Rua Eng. Carlos Stevenson, 362)",
    ficha:[["Unidades","164 em 2 torres: A com 9 pavimentos tipo (6 por andar) e B com 10 pavimentos tipo (10 por andar)"],["Garagem","3 subsolos · 1 ou 2 vagas por unidade (extra sob consulta)"],["Terreno","4.500 m²"]],
    lazer:["Piscina com deck molhado","Gourmet com piscina privativa","Salão de festas e sala de jantar","Fitness","Sport lounge","Quadra de esportes","Brinquedoteca e playground","Varanda dos temperos","Praças","Pet place","Drop zone","Wash & market"],
    cmp:{ter:"4.500 m²", tor:"2 (9 e 10 pavimentos tipo)", un:"164", var:"Sim — com churrasqueira nas plantas de 84 e 118 m²", dif:"Plantas de 1 a 3 dormitórios · lavabo · vaga extra sob consulta · 3 subsolos de garagem"} },
  { n:"Wide", c:"EBM", b:"Nova Campinas", t:"apto", m:[104], d:[3,3], su:true, v:"2", e:"2027-02", p:[[null,1300]], vis:"torre" },
  { n:"Tay", c:"Vanguard", b:"Nova Campinas", t:"apto", m:[68,77,96,105,144,198], d:[2,3], v:"2 ou 3", e:"2027-08", p:[[68,830],[77,935],[96,1250],[105,1400]], vis:"stand",
    tip:"Apartamentos de 68, 77, 96 e 105 m² privativos · penthouses de 144 e 198 m² · 2 ou 3 vagas",
    ficha:[["Tipologias","68, 77, 96 e 105 m² + penthouses de 144 e 198 m²"],["Vagas","2 ou 3 por unidade"],["Localização","Próximo à Av. Orosimbo Maia e à Av. Norte-Sul"]],
    lazer:["Piscina com deck","Quadra de areia","Espaço gourmet","Lounges e espaços de convivência","Portaria com port cochère"],
    cmp:{var:"Sim", dif:"Penthouses de 144 e 198 m² · 2 ou 3 vagas · lazer com paisagismo integrado"} },
  { n:"Belgravia", c:"Plaenge", b:"Nova Campinas", t:"apto", m:[134,276.5], d:[3,4], su:true, v:"2 a 4 + depósito", e:"2030-02", p:[[null,1450]], vis:"stand_dec",
    tip:"Tipo 134 m² privativos (136 m² com depósito) com 3 suítes e varanda coberta · garden com +25 m² de terraço descoberto · penthouse 276,5 m² com 4 suítes e sala íntima · depósito privativo de ~2,5 m² · 2 ou 3 vagas (penthouse 3 ou 4)",
    end:"Rua Rafael de Andrade Duarte — Nova Campinas",
    ficha:[["Torres","2"],["Vagas","2 ou 3 (tipo e garden), 3 ou 4 (penthouse) · 4 vagas de visitantes, uma com carregador elétrico"],["Depósito","Privativo, ~2,5 m²"],["Lazer","Áreas comuns equipadas, decoradas e climatizadas"],["Interiores","Bohrer Arquitetos"],["Garantia","Plaenge — seguro de entrega"]],
    lazer:["Piscina climatizada com raia de 25 m","Clubhouse privativo com piscina climatizada e churrasqueira","Pub","Fitness","Quadra poliesportiva","Brinquedoteca","Boulevard com fonte","Lobby","Pet place","Bicicletário","Port cochère e guarita com vidro de segurança","Espaço delivery"],
    cmp:{tor:"2", var:"Sim — varanda coberta (garden com terraço descoberto)", dif:"3 suítes · lavabo · cozinha aberta · depósito privativo · lazer climatizado · carregador elétrico nas vagas de visitante · seguro de entrega Plaenge"} },
  { n:"Velasca", c:"Arkesi", b:"Nova Campinas", t:"apto", m:[82,114], d:[2,3], su:true, v:"2", e:"2027-08", p:[[null,1200]], vis:"stand_dec" },

  // ── JD. PROENÇA ───────────────────────────────────────
  { n:"Eco Vila Primavera", c:"Furlan", b:"Jd. Proença", t:"apto", m:[67,77], d:[2,3], v:"2", e:"pronto", p:[[67,700],[77,845]], vis:"torre" },
  { n:"Upside", c:"Ytcon", b:"Jd. Proença", t:"apto", m:[68,87], d:[2,3], v:"1 e 2", e:"2028-04", p:[[68,800],[87,1100]], vis:"stand_dec" },

  // ── GUANABARA ─────────────────────────────────────────
  { n:"Liv Guanabara", c:"ADN", b:"Guanabara", t:"apto", m:[47.19,47.73], d:[2,2], suite:true, v:"1", e:"2029-07", p:[[null,530]], vis:"stand_dec",
    cmp:{ter:"1.964,98 m²", tor:"1 (subsolo + térreo + 16 andares)", un:"96", var:"Sim — varanda gourmet com ponto a gás para churrasqueira", dif:"Pé-direito de 2,60 m · suíte · ventilação natural no banheiro da suíte · ponto para máquina de lavar · depósito individual por andar (consultar)"},
    tip:"2 dormitórios (1 suíte) com varanda gourmet e ponto a gás para churrasqueira · apê centro 47,19 m² e apê canto de 47,37 a 47,73 m² · pé-direito 2,60 m · depósito individual por andar (consultar)",
    end:"Rua Doutor Cândido Gomide, 738 — Jardim Guanabara",
    ficha:[["Unidades","96 apartamentos em 1 torre (subsolo + térreo + 16 andares)"],["Vagas","108: 49 P, 47 M, 2 PCD e 10 de moto"],["Terreno","1.964,98 m²"],["Área construída","7.416,20 m²"],["Diferenciais","Áreas comuns entregues equipadas e decoradas · portaria 24h com CFTV · Wi-Fi e USB nas áreas comuns"]],
    lazer:["Piscina","Salão de festas","Academia","Coworking","Brinquedoteca"] },

  // ── CAMBUÍ ────────────────────────────────────────────
  { n:"Intento", c:"Bild", b:"Cambuí", t:"apto", m:[90,120], d:[2,3], su:true, v:"2 e 3", e:"2027-02", p:[[90,1200],[120,1350]], vis:"torre" },
  { n:"Verter", c:"AZO", b:"Cambuí", t:"apto", m:[154.09,154.83,293.78], d:[2,3], su:true, v:"3 (penthouse: 4)", e:"2026-02", p:[[null,2300]], vis:"nenhum",
    tip:"Vërtër Cambuí · 154 m²: 3 suítes ou 2 suítes com amplos closets e espaço para adega · elevador privativo · depósito privativo · penthouse de 293,78 m² com varandas em todas as suítes, home theater e 4 vagas",
    end:"Rua Dr. Guilherme da Silva — Cambuí",
    ficha:[["Tipologias","Finais 1 e 2 com 154,83 e 154,09 m² · penthouse 293,78 m²"],["Vagas","3 por apartamento (penthouse: 4) + depósito privativo"],["Arquitetura","Oliveira Cotta (arquitetura bioclimática)"],["Paisagismo","Marcelo Novaes"],["Tecnologia","Elevador privativo com biometria, persianas automatizadas, tomadas USB"],["Sustentabilidade","Ponto para carro elétrico por apto, previsão de placas fotovoltaicas, energia regenerativa nos elevadores"]],
    lazer:["Piscina adulto e infantil","Churrasqueira com forno de pizza","Salão de festas gourmet","Academia e espaço funcional","Coworking","Brinquedoteca e playground","Quadra recreativa","Fireplace e praça do espelho d'água","Praça da escultura","Mini market","Pet place","Espaço delivery e espaço Uber","Rooftop com lazer"],
    cmp:{tor:"1", var:"Sim — piso nivelado com a sala e forro de madeira", dif:"Elevador privativo com biometria · persianas automatizadas · tomada para toalheiro elétrico · suíte master com closet · despensa reversível · ponto para carro elétrico · depósito privativo"} },
  { n:"The Mark", c:"Plaenge", b:"Cambuí", t:"apto", m:[133,193], d:[3,4], su:true, v:"2 a 4", e:"2026-03", p:[[null,2400]], vis:"stand" },
  { n:"Pininfarina", c:"Plaenge", b:"Cambuí", t:"apto", m:[240,348], d:[3,4], su:true, v:"3 e 4", e:"2029-05", p:[[null,7000]], vis:"stand" },
  { n:"Autentic", c:"Plaenge", b:"Cambuí", t:"apto", m:[155], d:[3,3], su:true, v:"3", e:"2028-03", p:[[null,3000]], vis:"stand" },
  { n:"Luce Cambuí", c:"Tegra", b:"Cambuí", t:"apto", m:[85,110], d:[2,3], suite:true, v:"2 + depósito", vc:"coberta", e:"2026-11", p:[[85,1100],[110,1450]], vis:"torre",
    cmp:{ter:"3.382,71 m²", tor:"2 (Clari e Lumi)", un:"136", var:"Sim — terraço (110 m² com vista para o pôr do sol)", dif:"Depósito privativo de 2 m² · medição individual de água e energia · misturador na cozinha e banhos · ponto de água para geladeira · opcionais Tegra ID (fechadura eletrônica, churrasqueira a carvão, rede frigorígena p/ ar-condicionado, persianas motorizadas)"},
    tip:"85 m²: 3 dorms (1 suíte) ou 2 suítes · 110 m²: 3 suítes · cada unidade com depósito privativo de 2 m² (87 e 112 m² no total)",
    end:"Rua Américo Brasiliense, 443 — Cambuí",
    ficha:[["Unidades","136 em 2 torres (Clari e Lumi)"],["85 m²","66 unidades · 3 dorms (1 suíte) ou 2 suítes"],["110 m²","70 unidades · 3 suítes"],["Vagas","2 cobertas + 1 depósito privativo, vinculados"],["Terreno","3.382,71 m²"],["Arquitetura","Primi & Appoloni"],["Decoração","Debora Aguiar Arquitetos"],["Paisagismo","Neusa Nakata"],["Certificação","AQUA-HQE (sustentabilidade)"]],
    lazer:["Piscina com vista elevada","Fitness com sala de pilates","Family Space externo com churrasqueira e piscina","Family Space interno gourmet","Salão de festas","Salão de jogos","Brinquedoteca","Playground","Praça central com paisagismo","Bicicletário decorado","Delivery space","Carregador de carro elétrico","Portaria blindada e controle de acesso","Lazer em dois níveis"] },
  { n:"Ateliê", c:"ACT", b:"Cambuí", t:"apto", m:[43], d:[1,1], v:"1", e:"2025-12", p:[[null,600]], vis:"nenhum" },
  { n:"Yard", c:"Tegra", b:"Cambuí", t:"apto", m:[126], d:[3,3], su:true, v:"2 (vinculadas)", e:"pronto", p:[[null,1400]], vis:"torre",
    cmp:{end:"Rua Cel. Francisco Andrade Coutinho, 112 — Cambuí", ter:"3.333,75 m²", tor:"1 (29 pavimentos)", un:"100 (96 de 126 m² + 4 duplex de 221 m²)", m2:"126 m² e duplex de 221 m²", var:"Sim — terraço com laje nivelada à sala", dif:"Previsão de ar-condicionado na sala e dormitórios · persianas de enrolar com previsão de motorização · medição individual de água · misturador na cozinha e banhos · tomadas USB"},
    tip:"Yard Cambuí · 3 suítes · terraço com laje nivelada à sala · 4 apartamentos por andar · previsão de ar-condicionado na sala e dormitórios, persianas com previsão de motorização",
    ficha:[["Por andar","4 apartamentos"],["Vagas","Vinculadas às unidades"],["Áreas comuns","Entregues climatizadas, equipadas e decoradas"],["Infraestrutura","Gerador para elevadores de serviço e bombas · carregamento de carro elétrico · CFTV nos acessos"]],
    lazer:["Piscina adulto com raia de 25 m","Piscina adulto com deck molhado","Piscina infantil e solário","Fitness com apoio externo","Salão de festas com apoio externo","Espaço gourmet com churrasqueira e forno de pizza","Churrasqueira","Salão de jogos","Brinquedoteca","Playground","Quadra recreativa","Pet place","Praça de chegada e lobby","Bicicletário decorado"] },
  { n:"Vestra", c:"Setin", b:"Cambuí", t:"apto", m:[139,285], d:[3,3], su:true, v:"2 (demarcadas)", vc:"coberta", e:"pronto", p:[[null,1650]], vis:"torre",
    tip:"139 m² com 3 suítes · 1 apartamento garden de 285 m² com 3 suítes · previsão de ar-condicionado no living, terraço e dormitórios · living com porcelanato Portobello",
    end:"Rua Antônio Lapa, 118 — Cambuí",
    ficha:[["Unidades","73 em torre única (18 pavimentos, 4 por andar): 72 de 139 m² + 1 garden de 285 m²"],["Vagas","2 demarcadas por unidade, em 2 subsolos"],["Terreno","2.468,65 m²"],["Facilidades","Lockers inteligentes, central delivery, recarga para carro elétrico nas vagas de visitante"]],
    lazer:["Piscina adulto (16,4 x 4,8 m) e infantil com solário","Fitness","Salão de festas gourmet","Churrasqueira e lounge externo","Coworking","Lavanderia compartilhada OMO","Brinquedoteca e playground","Pet place","Bicicletário"],
    cmp:{ter:"2.468,65 m²", tor:"1 (18 pavimentos)", un:"73", var:"Sim — terraço com ponto de TV e previsão de ar-condicionado", dif:"3 suítes · tomadas USB nos dormitórios · cozinha com pontos para coifa, cooktop a gás, forno elétrico e lava-louças · persianas · piso vinílico nos dormitórios"} },
  { n:"Belleville", c:"Santo André", b:"Cambuí", t:"apto", m:[128], d:[3,3], su:true, v:"2 e 3", e:"2027-12", el:"Final de 2027", p:[[null,1800]], vis:"torre" },
  { n:"Grand Paysage", c:"Stéfani Nogueira e Copema", b:"Cambuí", t:"apto", m:[115.71,117.43], d:[3,3], su:true, v:"2", e:"pronto", p:[[null,1700]], vis:"torre",
    tip:"3 suítes · plantas de 115,71 m² e 117,43 m² (padrão ou opção do decorado com living ampliado)",
    end:"Rua General Osório, 2.240 — Cambuí",
    ficha:[["Unidades","76 em torre única (19 pavimentos tipo, 4 por andar)"],["Vagas","2 por apartamento"],["Elevadores","3 (2 sociais e 1 de serviço)"],["Terreno","2.375,46 m²"],["Área construída","14.492,09 m²"],["Lançamento","1º semestre de 2022"]],
    lazer:["Piscina com raia, piscina infantil, deck molhado e solarium","Fitness room e fitness outdoor","Quadra esportiva","Churrasqueira","Salão de festas e salão de festas infantil","Brinquedoteca e playground","Espaço teen","Coworking","Mini market","Delivery","Estação de carregamento para carro elétrico"],
    cmp:{ter:"2.375,46 m²", tor:"1 (19 pavimentos tipo)", un:"76", el:"3 (2 sociais e 1 de serviço)", var:"Sim — varanda integrada ao living", dif:"3 suítes · 4 apartamentos por andar · planta com opção de living ampliado"} },
  { n:"HOX", c:"Acro", b:"Cambuí", t:"apto", m:[31,38,56,58,61,83], d:null, tip:"Studio, apartamento e loft duplex", v:"1", e:"2029-08", p:[[31,650],[58,935],[61,1100],[83,1380]], vis:"stand_dec" },
  { n:"Edge Cambuí", c:"One Innovation e GNO", b:"Cambuí", t:"apto", m:[109,136,182], d:[2,3], su:true, v:"2 e 3 + depósito", e:"pronto", p:[[109,1550],[136,1700],[182,2500]], vis:"imovel", vo:"Visita ao apartamento",
    tip:"109 m² com 2 suítes e 2 vagas · 136 m² com 3 suítes e 2 vagas (terraço na suíte master; opção com sala de TV) · 182 m² com 3 suítes e 3 vagas (pé-direito de 5,50 m no living e terraço, elevador privativo) · depósito privativo no subsolo",
    end:"Rua Maria Monteiro, 725 — Cambuí",
    ficha:[["Unidades","67 em torre única (23 pavimentos, 3 por andar): 22 de 109 m², 22 de 136 m² e 23 de 182 m²"],["Vagas","Determinadas e vinculadas, garagem com piso epóxi · 1 vaga por unidade com infra para carro elétrico"],["Depósito","Privativo no subsolo (2,50 m²)"],["Terreno","2.400 m²"],["Arquitetura","HMK"],["Paisagismo","Marcelo Vassalo"],["Decoração","DP Barros"]],
    lazer:["Piscina com raia de 25 m, deck molhado, solarium e gazebos","Spa com cascata","Espaço wellness com spa aquecido e sauna","Quadra de beach tennis (medidas oficiais)","Espaço fitness com equipamentos profissionais","Festas gourmet com terraço","Terraço gourmet","Casa de campo privativa com piscina","Playground e espaço kids/baby","Bicicletário com bike repair","Portaria blindada com port cochère","Espaço delivery"],
    cmp:{ter:"2.400 m²", tor:"1 (23 pavimentos)", un:"67", var:"Sim — terraço com piso nivelado e previsão de churrasqueira a gás", dif:"Infra para ar-condicionado cassete · persianas integradas com previsão de automação · terraço técnico independente · previsão de coifa · ventilação natural nos banhos · depósito privativo · elevador transfer para o lazer"} },
  { n:"Vivio", c:"Congesa", b:"Cambuí", t:"apto", m:[112,114], d:[3,3], su:true, v:"2 e 3", e:"2028-01", p:[[null,1800]], vis:"stand_dec", obs:"O PDF traz informação conflitante (\"tem stand e decorado\" e \"não tem stand nem decorado\") — confirmar antes de agendar." },
  { n:"Gallery Cambuí", c:"Grucom", b:"Cambuí", t:"apto", m:[73], d:[2,2], su:true, v:"1 e 2", e:"2029-05", p:[[null,1150]], vis:"stand_dec" },
  { n:"Mood Cambuí", c:"Congesa", b:"Cambuí", t:"apto", m:[76], d:[2,2], su:true, v:"1 e 2", e:"pronto", p:[[null,1240]], vis:"imovel", vo:"Visita no condomínio" },

  // ── IGUATEMI ──────────────────────────────────────────
  { n:"Avenida 105", c:"Building", b:"Iguatemi", t:"apto", m:[154,158], d:[3,4], v:"3 + depósito", e:"2028-04", p:[[null,2300]], vis:"stand_dec",
    tip:"3 e 4 dormitórios com suíte master com varanda e varandas nos quartos · coberturas duplex · todos os apartamentos com vista permanente para o norte · personalização de acabamentos (Building Privilege)",
    end:"Avenida Rotary, 105 — bairro Casa Figueira (ao lado do Shopping Iguatemi)",
    ficha:[["Bairro planejado","1º empreendimento do Casa Figueira (complexo de uso misto com 240 mil m² de áreas verdes)"],["Garagem","Pintura epóxi, depósito privativo, infra para carro elétrico"],["Área de lazer","Aprox. 4.800 m² externos, entregues climatizados"],["Fachada","Fachada viva com brises metálicos perfurados Hunter Douglas"],["Conforto","Manta acústica entre lajes, ventilação cruzada, área técnica para multisplit"]],
    lazer:["Piscina climatizada com borda infinita","Casa de festas com piscina privativa","Academia com equipamentos profissionais e fitness externo","Espaço pilates","Quadra de areia","Parquinho naturalizado e brinquedoteca","Salão de jogos","Coworking e sala de reunião","Lounges e espaço gourmet","Redário","Pomar e floresta de bolso","Bicicletário","Sala para delivery"],
    cmp:{var:"Sim — suíte master com varanda e porta balcão com varanda nos quartos", dif:"Vista permanente para o norte · ponto para coifa com exaustão externa · previsão para churrasqueira a carvão · infra para ar-condicionado (multisplit) · aquecimento a gás · metais monocomando · ralo linear · depósito privativo"} },
  { n:"Tresor", c:"Furlan e GNO", b:"Iguatemi", t:"apto", m:[80,100], d:[2,3], v:"2 ou 3 + depósito", e:"2028-12", p:[[80,1000],[100,1200]], vis:"stand_dec",
    tip:"Trésor · 100 m²: 3 dorms (1 suíte) com lavabo ou 2 suítes com sala ampliada · 80 m²: 2 suítes com lavabo · gardens com quintais privativos (64 m² no de 80 m²; 91 a 136 m² no de 100 m²) · varanda nivelada com a sala",
    end:"Rua Sargento Mauro dos Santos, 66 — Jardim Alto da Barra (perto do Shopping Iguatemi)",
    ficha:[["Torres","2 (subsolo, térreo, lazer e 6 pavimentos tipo, 6 apartamentos por andar)"],["Vagas","2 ou 3 por unidade + depósito privativo"],["Terreno","7.650,64 m², em frente a uma grande praça"],["Arquitetura","HMK"],["Interiores","AL7 Arquitetura"],["Paisagismo","Marcelo Novaes"]],
    lazer:["Piscina adulto com spa e deck molhado","Piscina infantil e solário","2 casas de campo com piscina privativa","Quadra de beach tennis","Quadra recreativa","Fitness e academia externa","Salão de festas","Churrasqueira","Coworking e salas de reunião","Brinquedoteca e playground","Espaço zen e lounges externos","Pet place","Bicicletário","Portaria com clausura e sala de encomendas"],
    cmp:{ter:"7.650,64 m²", tor:"2 (6 pavimentos tipo)", var:"Sim — varanda nivelada com a sala", dif:"Área técnica de ar-condicionado separada da varanda · persiana integrada nos dormitórios · depósito privativo · opção garden com quintal"} },
  { n:"Hípica Boulevard", c:"Santo André", b:"Iguatemi", t:"apto", m:[91], d:[3,3], v:"2", e:"pronto", p:[[null,1100]], vis:"nenhum" },

  // ── GALLERIA ──────────────────────────────────────────
  { n:"Sensia Galleria", c:"Sensia", b:"Galleria", t:"apto", m:[61,74], d:[2,3], v:"1 e 2", e:"pronto", p:[[61,510],[74,650]], vis:"stand" },
  { n:"City Galleria", c:"MRV", b:"Galleria", t:"apto", m:[45.49,45.7,53.28,53.59], d:[2,2], v:"1", e:"2028-07", p:[[45,430],[53,530]], vis:"stand_dec",
    tip:"2 dormitórios com opção de suíte e de varanda: 45,70 m² · 45,49 m² com varanda · 53,59 m² com suíte · 53,28 m² com suíte e varanda · térreo com área privativa de 12,45 a 27,73 m² (sem varanda)",
    end:"Rua Carlos Luiz Barroso Ehrenberg, 181 — Residencial Galeria Garden",
    ficha:[["Unidades","528 em 3 torres (3 elevadores por torre)"],["Vagas","519 de carro (11 PCD) + 27 de moto"],["Terreno","10.429,80 m²"]],
    lazer:["Piscinas adulto e infantil","Salão de festas","Espaço gourmet e churrasqueira","Quadra de areia","Sala de estudos","Playground e espaço kids","Pet place","Redário e gazebo","Bicicletário e praça"],
    cmp:{ter:"10.429,80 m²", tor:"3", un:"528", el:"3 por torre", var:"Opção de varanda", dif:"Opção de suíte · opção de área privativa no térreo · vista para a cidade (consultar unidades)"} },
  { n:"Alto do Galleria II", c:"Zuma", b:"Galleria", t:"apto", m:[41.39,42.66], d:[2,2], v:"1 (carro ou moto)", e:"2029-08", p:[[null,320]], vis:"stand_dec",
    cmp:{ter:"2.818,74 m²", tor:"1", un:"108", el:"2", var:"Sim", dif:"Previsão de ar-condicionado no quarto de casal · piso cerâmico na cozinha, área de serviço e banheiro (sala e quartos no contrapiso)"},
    tip:"2 dormitórios com varanda · planta de ponta 41,39 m² (finais 1, 2, 5 e 6) e planta de meio 42,66 m² (finais 3 e 4) · previsão de ar-condicionado no quarto do casal",
    end:"Rua Antônio Pavin, 227 — Jardim Conceição",
    ficha:[["Unidades","108 apartamentos em torre única"],["Vagas","89 aptos com vaga de carro, 3 com carro + moto e 16 só com vaga de moto"],["Visitantes","5 vagas"],["Elevadores","2"],["Terreno","2.818,74 m²"],["Construtora","Zuma Engenharia"]],
    lazer:["Piscina","Playground","Academia","Salão gourmet com churrasqueira","Espaço multiuso","Bicicletário (10 vagas)","Portaria"] },

  // ── SWISS PARK ────────────────────────────────────────
  { n:"Swiss Garden", c:"Sensia", b:"Swiss Park", t:"apto", m:[61,74], d:[2,3], v:"1 e 2", e:"2028-12", p:[[61,600],[74,760]], vis:"stand_dec" },
  { n:"Best View", c:"F.A. Oliva", b:"Swiss Park", t:"apto", m:[66,78], d:[2,3], v:null, e:"2027-04", p:[[66,700],[78,800]], vis:"stand" },

  // ── JD. AURÉLIA ───────────────────────────────────────
  { n:"Reserva Perfetto", c:"Stan", b:"Jd. Aurélia", t:"apto", m:[63,76,97], d:[2,3], suite:true, v:"1 ou 2 (determinadas)", e:"pronto", p:[[63,620],[76,750],[97,null]], vis:"nenhum",
    tip:"63 m²: 2 dorms (1 suíte) · 76 m²: 3 dorms (1 suíte) ou 2 dorms com sala ampliada · 97 m²: 3 dorms (1 suíte) · terraço entregue com churrasqueira, bancada, cuba e coifa · opções de cozinha aberta · unidades garden",
    end:"Av. José Mário de Arruda Toledo, 550 — Jardim Aurélia",
    ficha:[["Torres","2 (Torre 1 Ipê e Torre 2 Figueira)"],["Garagem","Edifício-garagem com subsolo · 1 ou 2 vagas determinadas"],["Unidades","Infra para ar-condicionado na sala e dormitórios, persianas integradas, aquecedor de passagem (infra), medição individual de água e gás"]],
    lazer:["Piscinas adulto e infantil com solarium e deck molhado","Quadra poliesportiva coberta","Fitness e deck para alongamento","Salão de festas","Espaço gourmet","Churrasqueiras com forno de pizza","Salão de jogos","Brinquedoteca e playground","Praças e espaços com pergolados","Acessos com clausura"],
    cmp:{tor:"2 (Ipê e Figueira)", var:"Sim — terraço com churrasqueira, bancada, cuba e coifa", dif:"Persianas integradas · infra para ar-condicionado · medição individual de água e gás · opção de cozinha aberta · unidades garden"} },
  { n:"Terrace Home Resort", c:"Soedil", b:"Jd. Aurélia", t:"apto", m:[69], d:[3,3], v:"2", e:"2028-02", p:[[null,720]], vis:"stand_dec" },
  { n:"Spot", c:"Ytcon", b:"Jd. Aurélia", t:"apto", m:[66], d:[2,2], v:"1", e:"2027-05", p:[[null,530]], vis:"stand_dec" },

  // ── BONFIM ────────────────────────────────────────────
  { n:"Maxi Bonfim", c:"HM", b:"Bonfim", t:"apto", m:[64.49], d:[2,3], v:"1", vc:"coberta", e:"pronto", p:[[null,510]], vis:"nenhum",
    cmp:{ter:"8.829,18 m²", tor:"5 (térreo + 17 pavimentos)", var:"Sim — varanda gourmet com churrasqueira a carvão", dif:"Área técnica e pontos para ar-condicionado · ponto de gás · bancadas de granito · piso cerâmico na cozinha, área de serviço, varanda e banheiros · pé-direito de 2,60 m"},
    tip:"HM Maxi Campinas · 64,49 m² com 3 dorms ou 2 dorms com sala estendida (também versão PCD) · varanda gourmet com churrasqueira a carvão · área técnica para ar-condicionado",
    end:"Rua da Constituição esquina com Rua Luiz Gama — Bonfim",
    ficha:[["Torres","5 (térreo + 17 pavimentos), 4 unidades por andar"],["Garagem","Edifício-garagem, 1 vaga por unidade"],["Terreno","8.829,18 m²"],["PCD","Unidades adaptáveis no 17º pavimento"]],
    lazer:["Piscinas adulto e infantil com prainha","Beach arena","Quadra poliesportiva","Espaço fitness","Espaço gourmet duplo","Quiosque churrasco","Coworking","Playground e espaço play kids","Pomar","Praça boas-vindas","Minimercado","Portaria de pedestres com porte-cochère","Lazer entregue equipado e decorado"] },
  { n:"Blend", c:"Living", b:"Bonfim", t:"apto", m:[55,66,80], d:[2,3], v:"1 e 2", e:"pronto", p:[[55,null],[66,null],[80,860]], vis:"stand" },

  // ── TAQUARAL ──────────────────────────────────────────
  { n:"Sensia Taquaral", c:"Sensia", b:"Taquaral", t:"apto", m:[61.17,63.22,122.32], d:[2,2], suite:true, v:"1 e 2", vc:"coberta", e:"2027-08", p:[[null,630]], vis:"stand_dec",
    cmp:{ter:"3.139,41 m²", tor:"1 (3 pavimentos de garagem + 14 de apartamentos)", un:"108", var:"Sim", dif:"Planta flexível · cobertura linear de 122,32 m²"},
    tip:"2 quartos com suíte e varanda · tipo meio 61,17 m² e tipo ponta 63,22 m² · cobertura linear de 2 quartos com 122,32 m² · planta flexível",
    end:"Rua Rodolfo Noronha, 47 — Jardim Nossa Senhora Auxiliadora (2ª portaria: Rua Dr. Oswaldo Cruz, 799)",
    ficha:[["Unidades","108 em torre única (14 pavimentos de apartamentos)"],["Garagem","Edifício-garagem com 3 pavimentos"],["Terreno","3.139,41 m²"],["Construção","Alvenaria + drywall"],["Incorporadora","Sensia (grupo MRV)"]],
    lazer:["Piscina adulto e infantil com deck molhado","Quadra de beach tennis","Academia equipada","Spa e sauna","Salão de festas","Coworking e sala de reunião","Praça de convivência","Playground e espaço kids","Bicicletário coberto","Vaga para carro elétrico","Lazer entregue equipado e decorado"] },
  { n:"Yees Taquaral", c:"Yees (JJR Empreendimentos)", b:"Taquaral", t:"apto", m:[35.04,55.37], d:[1,2], v:"1 + depósito", e:"2027-07", p:[[null,650]], vis:"stand",
    tip:"Taquaral Residence · plantas de 35,04 a 55,37 m² com 1 e 2 dormitórios · cada unidade com vaga e depósito",
    end:"Av. Monsenhor Jerônimo Baggio, 444 — Jardim Nossa Senhora Auxiliadora",
    ficha:[["Unidades","103 em torre única (8 por andar)"],["Vagas","103 + 2 PCD + 3 de visitantes + 8 de moto · 103 depósitos"],["Terreno","2.600 m²"],["Área construída","8.626,45 m²"]],
    lazer:["Piscina no rooftop","Lounge com fireplace","Quadra de areia","Academia e espaço funcional","Brinquedoteca","Playground","Espaço gourmet e salão de festas"],
    cmp:{ter:"2.600 m²", tor:"1", un:"103", dif:"Depósito por unidade · lazer no rooftop"} },

  // ── PARQUE PRADO ──────────────────────────────────────
  { n:"Casa Prado", c:"Riva", b:"Parque Prado", t:"apto", m:[69,96], d:[2,3], v:"1 e 2", e:"2028-08", p:[[69,750],[96,1000]], vis:"stand_dec" },
  { n:"Florae Jambeiro", c:"Vitta", b:"Parque Prado", t:"apto", m:[42.99,45.02], d:[2,2], v:"1", e:"2028-12", p:[[null,340]], vis:"virtual",
    cmp:{tor:"2", dif:"Plantas de 2 dormitórios de 42,99 a 45,02 m² · gardens privativos no térreo · planta adaptável PcD · infraestrutura Mercado Vitta"},
    tip:"2 dormitórios · plantas tipo de 42,99, 43,82, 43,89, 44,86 e 45,02 m² · térreo com garden privativo (44,86 m² + 4,25 m² ou + 20,28 m² + 4,25 m², entregue gramado e descoberto) · planta PcD de 45,02 m² (1 dormitório, mediante adaptação)",
    end:"Rua Florindo Matos Pereira, 570 — Parque Prado (região do Jambeiro)",
    ficha:[["Torres","2"],["Por andar","Finais 01 a 10"],["Segurança","Guarita com vidro reflexivo, controle de acesso com porteiro eletrônico, espera de segurança para pedestres e previsão para automação condominial"],["Piscinas","Adulto com raia de aprox. 14 m, solarium e prainha; acessível; infantil; fechadas em gradil"],["Área verde","Área de preservação permanente no terreno"],["Localização","Rodovia Anhanguera 2 min · Av. Baden Powell 5 min · Shopping 7 min (de carro)"]],
    lazer:["Piscina adulto com raia e prainha","Piscina infantil","Deck molhado e solarium","Espaço fitness","Fitness ao ar livre","Salão de festas","Churrasqueira e espaço churrasco","Pub torcedor","Espaço cinema","Brinquedoteca","Play kids","Oficina criativa","Praça de encontro","Espaço repouso","Espaço mirante","Espaço pet","Car wash","Mini mercado (infraestrutura Mercado Vitta)","Bicicletário"] },
  { n:"Portal dos Jatobás", suite:true, c:"MRV", b:"Parque Prado", t:"apto", m:[44], d:[2,2], v:"até 1", e:"2029-12", el:"2029", p:[[null,290],[null,360]], vis:"stand", obs:"Com ou sem suíte. Preço de R$ 290 mil a R$ 360 mil." },

  // ── CASAS ─────────────────────────────────────────────
  { n:"Oni Dijon Taquaral", c:"Peconi", b:"Taquaral", t:"casa", m:[128.94,166.89,171.75], d:[3,3], su:true, v:"2", e:"2026-12", p:[[null,1500]], vis:"dec",
    cmp:{end:"Av. Milton Christini, 1.076 (esquina com a Av. Almeida Garret) — Parque Taquaral", tor:"Não se aplica (casas)", un:"21 casas", el:"Não se aplica (casas)", var:"Rooftop privativo com churrasqueira e área preparada para spa", dif:"Infra de automação House.Oni (fechadura digital, iluminação, persianas, ar-condicionado) · tomada para carro elétrico na garagem · suíte master com closet"},
    tip:"Casas de 3 pavimentos: térreo com sala de estar e jantar, lavabo e cozinha americana · 1º pavimento com 3 suítes (master com closet) · rooftop com churrasqueira, banheiro e área preparada para spa · 4 plantas: Íris e Tulipa (171,75 m²), Lavanda (166,89 m²) e Rosa (128,94 m²)",
    ficha:[["Casas","21 em condomínio fechado (OniDijon Résidence)"],["Garagem","2 vagas por casa, com tomada para carro elétrico"],["Automação","Infraestrutura House.Oni (fechadura digital, iluminação, persianas, ar-condicionado)"],["Segurança","Portaria e guarita blindadas, pulmão de segurança, portão automatizado, preparado para reconhecimento facial"],["Localização","2 min da Lagoa do Taquaral · 3 min do The Mall · 4 min do Shopping Dom Pedro"]],
    lazer:["Rooftop privativo com churrasqueira e área para spa/jacuzzi","Salão de festas","Academia","Playground","Pet place"] },
  { n:"Lake Louise Taquaral", c:"CPN Engenharia", b:"Taquaral", t:"casa", m:[136.72,195.57], d:[3,3], su:true, v:"2", vc:"coberta", e:"2027-03", p:[[136.72,1700],[195.57,2150]], vis:"dec",
    tip:"Casas isoladas (não geminadas) com 3 suítes · Casa Iris 136,72 m² (térreo + superior) · Casa Silene 195,57 m² com rooftop privativo (gourmet coberto, lavabo, infra para spa e churrasqueira)",
    end:"Rua Miosótis, 65 — Taquaral",
    ficha:[["Casas","37 em condomínio fechado: 15 Iris (136,72 m²) e 22 Silene (195,57 m²)"],["Garagem","2 vagas por casa, totalmente cobertas (laje maciça) · vagas para visitantes"],["Terreno","8.166,80 m²"],["Área construída","6.057,36 m²"],["Arquitetura","XOK Arquitetos"],["Interiores","Juruá"],["Paisagismo","Alexandre Furcolin"],["Segurança","Guarita com clausura social e de serviço, portão automático, infra para CFTV"]],
    lazer:["Piscinas adulto e infantil com solarium","Espaço gourmet com varanda integrada","Fitness equipado e climatizado","Brinquedoteca","Playground","Pet place","Alameda com fiação subterrânea","Espaço delivery","Mall com acesso independente (Taquaral Mall)","Áreas comuns entregues equipadas e decoradas"],
    cmp:{ter:"8.166,80 m²", tor:"Casas isoladas (37)", un:"37", var:"Rooftop privativo na Casa Silene", dif:"Casas não geminadas · forro de gesso em todos os ambientes · água quente na cozinha e banheiros · infra para ar-condicionado · lavabo com ventilação natural · entradas social e de serviço independentes · lavanderia com banheiro de serviço"} },
  { n:"Club House Taquaral", c:"Concini", b:"Taquaral", t:"casa", m:[167], d:[3,3], su:true, v:"2", e:"2027-06", p:[[null,1400]], vis:"dec", tip:"3 pavimentos" },
  { n:"Quinta do Miranda Taquaral", c:"Miranda", b:"Taquaral", t:"casa", m:[174], d:[3,3], su:true, v:"2", e:"pronto", p:[[null,1700]], vis:"imovel", vo:"Visita na casa", tip:"3 pavimentos" },
  { n:"Moreira 1730", suite:true, c:"Não informada", b:"Mansões Santo Antônio", t:"casa", m:[158], d:[3,3], v:"2", e:"pronto", p:[[null,1300]], vis:"imovel", vo:"Visita na casa", tip:"3 dorms (1 suíte) · 3 pavimentos" },
  { n:"House Me Taquaral", suite:true, c:"Ravic e ACT", b:"Taquaral", t:"casa", m:[130], d:[3,3], v:"2 (privativas)", e:"pronto", p:[[null,1250]], vis:"imovel", vo:"Visita na casa",
    tip:"Casas de 130 m² com 3 dormitórios (1 suíte), lavabo, pé-direito de 2,70 m e área externa exclusiva · duas versões: casa térrea ou casa com rooftop",
    ficha:[["Tipologias","Casa térrea ou casa com rooftop, ambas com 130 m² privativos"],["Vagas","2 privativas por casa"],["Localização","Em frente à Praça Alfredo Elias Júnior · 2 min da PUC · 5 min do Parque Taquaral"]],
    lazer:["Piscina com solário","Espaço gourmet com churrasqueira","Academia","Quadra suspensa de beach tennis com lounge","Praça do vinho","Playground"],
    cmp:{tor:"Casas (condomínio)", var:"Área externa privativa (rooftop na versão sobrado)", dif:"Pé-direito de 2,70 m · lavabo · área externa exclusiva com sugestão de churrasqueira ou fireplace"} },
  { n:"Casa da Mata Gramado", suite:true, c:"AZO e Izix", b:"Gramado", t:"casa", m:[187,216], d:[3,4], v:"3 ou 4", e:"2028-01", p:[[null,2350]], vis:"stand_dec",
    tip:"Casa Aura 187 m²: 3 suítes ou 2 suítes com sala íntima · 3 vagas · Casa Petra 216 m²: 3 suítes ou 4 dorms (2 suítes) · 4 vagas · 2 pavimentos, pé-direito duplo no hall, previsão para elevador residencial",
    end:"Av. Professora Déa Ehrhardt Carvalho, 1.400 — Gramado",
    ficha:[["Casas","60 em condomínio: 37 Aura (187 m²) e 23 Petra (216 m²)"],["Terreno","29.482 m² junto à mata"],["Unidades","Rede frigorígena de ar-condicionado nos dormitórios, infra para carregador de carro elétrico, espaço para 2 máquinas lava e seca"],["Segurança","Guarita blindada, eclusa de veículos, espaço encomendas"],["Certificação","EDGE e Casa Equilibrada"]],
    lazer:["Piscina-praia com raia de 25 m","Borda infinita e espelho d'água","Piscina infantil","Academia e espaço pilates (90 m²)","Quadra de beach tennis","Chute a gol","Salão de festas","Espaço gourmet","Sala de reunião","Brinquedoteca e playground","Mirante contemplativo","Redário e floresta de bolso","Horta de temperos","Praça de encontro","Espaço pet com vaga para pet care","Minimercado"],
    cmp:{ter:"29.482 m²", tor:"Casas (60)", un:"60", var:"Varanda gourmet integrada ao living", dif:"Previsão para elevador residencial · pé-direito duplo no hall · rede frigorígena de ar-condicionado · infra para carregador de carro elétrico · suíte master com closet · certificação EDGE"} },
  { n:"Maziero Betel", c:"Simoplan", b:"Betel (Paulínia)", t:"casa", m:[137.38,140.01], d:[3,3], su:true, v:"2", vc:"coberta", e:"2029-04", p:[[null,1500]], vis:"stand_dec",
    tip:"Residencial Maziero · casa térrea 137,38 m² ou sobrado 140,01 m², ambas com 3 suítes · casas isoladas (3 m entre elas) · terreno médio de 217 a 282 m² · infra para churrasqueira, pia e spa no quintal",
    end:"Av. Alexandre Cazellato, 2.730 — Betel, Paulínia",
    ficha:[["Casas","66 em condomínio: 31 térreas e 35 sobrados"],["Garagem","2 vagas cobertas por casa, com previsão para carregamento de carro elétrico"],["Terreno","25.020,16 m² (121 m de frente para a Av. Cazellato)"],["Acabamento","Porcelanato 80x80 em todos os ambientes, forro de gesso, fechadura digital com biometria, previsão de ar-condicionado"],["Construção","T&S Engenharia"],["Personalização","Programa Tudo Pronto Simoplan (itens instalados antes da entrega)"]],
    lazer:["Piscina adulto e infantil com deck molhado e espelho d'água","Quadra de beach tennis","Mini campo de futebol","Academia equipada com ar-condicionado","Espaço zen","Salão de festas com terraço e cozinha","Churrasqueira","Playground","Espaço delivery","Portaria com 2 guaritas (24h)"],
    cmp:{ter:"25.020,16 m²", tor:"Casas (66)", un:"66", var:"Área coberta no quintal com infra para churrasqueira e spa", dif:"Casas isoladas · 3 suítes · porcelanato 80x80 · fechadura biométrica · aquecimento a gás · previsão de ar-condicionado · carregador de carro elétrico · ralo linear"} },
  { n:"Casa Bella", c:"GNO e Incorpi", b:"Alphaville", t:"casa", m:[137,149,177], d:[3,3], su:true, v:"2", vc:"coberta", e:"2028-05", p:[[null,2000]], vis:"stand_dec",
    tip:"3 plantas, todas com 3 suítes e varanda gourmet integrada: Vereda 137 m² (térrea) · Harmonia 149 m² · Horizonte 177 m² (sobrado com sala íntima) · quintal com espaço para piscina",
    ficha:[["Garagem","Coberta para 2 carros"],["Ruas","Alamedas de 14 m (8 m de pista + 3 m de passeio arborizado de cada lado)"],["Casas","Sem divisa direta com a rua · entradas social e de serviço independentes"],["Acabamento","Porcelanato na área social, cozinha e banheiros · infra para ar-condicionado em quartos e sala · ralo linear"],["Bairro planejado","590 mil m² de áreas verdes, parque linear de 3 km, 11 praças, fiação subterrânea e gás encanado"],["Paisagismo","Marcelo Novaes"],["Arquitetura","Xok Arquitetos"]],
    lazer:["Casa gourmet com deck, entregue equipada e mobiliada","Piscina com deck","Fitness","Praça central e jardim de convívio","Playground"],
    cmp:{tor:"Casas (condomínio)", var:"Varanda gourmet integrada à sala de jantar", dif:"3 suítes em todas as plantas · quintal com espaço para piscina · garagem coberta para 2 carros · porcelanato · infra para ar-condicionado · ralo linear · entradas independentes"} },
  { n:"Arborais Alta Vista", c:"Congesa", b:"Alphaville", t:"casa", m:[160,195], d:[3,4], su:true, v:"2 e 3", e:"2028-11", p:[[null,2400]], vis:"stand_dec" },
  { n:"Alpha Housing", c:"Não informada", b:"Alphaville", t:"casa", m:[120], d:[3,3], su:true, v:"2", e:"pronto", p:[[null,1400]], vis:"imovel", vo:"Visita na casa" },
  { n:"Lauzanne", c:"Santo André", b:"Não informado", t:"casa", m:[208], d:[3,4], su:true, v:"4", e:"2026-12", p:[[null,1550]], vis:"dec", vo:"Casa decorada" },
  { n:"Villa Vita Taquaral", c:"I7", b:"Taquaral", t:"casa", m:[89,113,129], d:[2,3], su:true, v:"1 ou 2", e:"2028-06", p:[[null,1100]], vis:"nenhum",
    tip:"Sobrados com quintal (não computado na área): Casa Bem-Estar 89 m² com 2 suítes + office (1 ou 2 vagas) · Casa Aconchego 113 m² com 3 suítes (2 vagas) · Casa Requinte 129 m² com 3 suítes (2 vagas)",
    end:"Rua Émerson José Moreira, 500 — Parque Taquaral",
    ficha:[["Casas","36 em condomínio"],["Unidades","Pontos de ar-condicionado na sala e dormitórios, piso em todos os ambientes, ralo linear, fechadura digital, entrada de serviço separada"],["Infraestrutura","Fiação subterrânea, pressurizador de água, estrutura para portaria remota"]],
    lazer:["Piscinas adulto e infantil com deck molhado","Academia","Espaço gourmet e salão de festas","Open office com sala de reunião e copa","Estúdio","Brinquedoteca","Sala games","Brinquedão externo","Pet place","Vending machines"],
    cmp:{tor:"Casas (36)", un:"36", var:"Quintal privativo", dif:"2 ou 3 suítes · opção com office · pontos de ar-condicionado · ralo linear · fechadura digital · fiação subterrânea"} },
  { n:"TopLife Nova Campinas Park", c:"TopLife", b:"Nova Campinas", t:"apto", m:[46.71,46.77,49.02,49.11,50.65], d:[2,2], su:true, suite:true, v:"1 ou 2", vc:"ambas", fgts:false, inv:true, e:"2029-12", el:"2029", p:[[null,488],[null,613]], vis:"nenhum", vo:"A confirmar",
    tip:"2 dorms com suíte e varanda gourmet (46,71 a 50,65 m²) · 4 gardens no térreo com área privativa descoberta (62,50 a 71,13 m²)",
    end:"Avenida Imperatriz Dona Tereza Cristina, 980 — Nova Campinas",
    ficha:[["Unidades","64 em torre única (subsolo + térreo + 10 pavimentos tipo, 6 por andar, 4 gardens)"],["Terreno","1.494,60 m²"],["Arquitetura","TBR Arquitetura"],["Registro","R.13 da matrícula 29.900 (02/03/2026)"],["Tabela","Pré-lançamento, válida até 31/10/2026"]],
    lazer:["Piscina com solário e deck","Mini quadra esportiva","Playground","Espaço kids","Espaço fitness","Coworking","Espaço gourmet","Lavanderia","Marketplace","Bicicletário","Portaria"],
    cmp:{ter:"1.494,60 m²", tor:"1 (subsolo + térreo + 10 pavimentos)", un:"64", var:"Sim — varanda gourmet", dif:"2 dorms com suíte · opção garden com área privativa descoberta · 1 ou 2 vagas"} },
];
